

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO postgres;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO postgres;

--
-- Name: languages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.languages (
    id integer NOT NULL,
    language_tag character varying(255) NOT NULL
);


ALTER TABLE public.languages OWNER TO postgres;

--
-- Name: languages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.languages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.languages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: namespaces; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.namespaces (
    id integer NOT NULL,
    project_id integer NOT NULL,
    name character varying(255) NOT NULL,
    reference_url character varying(255) NOT NULL
);


ALTER TABLE public.namespaces OWNER TO postgres;

--
-- Name: namespaces_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.namespaces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.namespaces_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_language_status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_language_status (
    id integer NOT NULL,
    project_id integer,
    language_id integer,
    published boolean DEFAULT false,
    published_at timestamp without time zone
);


ALTER TABLE public.project_language_status OWNER TO postgres;

--
-- Name: project_language_status_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_language_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_language_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.projects (
    id integer NOT NULL,
    slug character varying(255) NOT NULL,
    deleted boolean DEFAULT false
);


ALTER TABLE public.projects OWNER TO postgres;

--
-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: translation_keys; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.translation_keys (
    id integer NOT NULL,
    namespace_id integer NOT NULL,
    key character varying(255) NOT NULL,
    reference_value character varying(2000)
);


ALTER TABLE public.translation_keys OWNER TO postgres;

--
-- Name: translation_keys_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.translation_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.translation_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: translation_values; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.translation_values (
    id integer NOT NULL,
    translation_key_id integer NOT NULL,
    language_id integer NOT NULL,
    value character varying(2000) NOT NULL
);


ALTER TABLE public.translation_values OWNER TO postgres;

--
-- Name: translation_values_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.translation_values ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.translation_values_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: postgres
--


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: languages languages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.languages
    ADD CONSTRAINT languages_pkey PRIMARY KEY (id);


--
-- Name: namespaces namespaces_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.namespaces
    ADD CONSTRAINT namespaces_pkey PRIMARY KEY (id);


--
-- Name: project_language_status project_language_status_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_language_status
    ADD CONSTRAINT project_language_status_pkey PRIMARY KEY (id);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- Name: translation_keys translation_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.translation_keys
    ADD CONSTRAINT translation_keys_pkey PRIMARY KEY (id);


--
-- Name: translation_values translation_values_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.translation_values
    ADD CONSTRAINT translation_values_pkey PRIMARY KEY (id);


--
-- Name: IX_projects_deleted; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_projects_deleted" ON public.projects USING btree (deleted);


--
-- Name: UI_namespaces_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UI_namespaces_name" ON public.namespaces USING btree (name, project_id);


--
-- Name: UI_project_language; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UI_project_language" ON public.project_language_status USING btree (project_id, language_id);


--
-- Name: UI_projects_slug; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UI_projects_slug" ON public.projects USING btree (slug);


--
-- Name: UI_translation_keys_namespace_key; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UI_translation_keys_namespace_key" ON public.translation_keys USING btree (key, namespace_id);


--
-- Name: translation_keys FK_namespace_translation_key; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.translation_keys
    ADD CONSTRAINT "FK_namespace_translation_key" FOREIGN KEY (namespace_id) REFERENCES public.namespaces(id) ON DELETE CASCADE;


--
-- Name: project_language_status FK_project_language_status_language; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_language_status
    ADD CONSTRAINT "FK_project_language_status_language" FOREIGN KEY (language_id) REFERENCES public.languages(id);


--
-- Name: project_language_status FK_project_language_status_project; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_language_status
    ADD CONSTRAINT "FK_project_language_status_project" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: namespaces FK_project_namespace; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.namespaces
    ADD CONSTRAINT "FK_project_namespace" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: translation_values FK_translation_key_value; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.translation_values
    ADD CONSTRAINT "FK_translation_key_value" FOREIGN KEY (translation_key_id) REFERENCES public.translation_keys(id) ON DELETE CASCADE;


--
-- Name: translation_values FK_translation_language; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.translation_values
    ADD CONSTRAINT "FK_translation_language" FOREIGN KEY (language_id) REFERENCES public.languages(id);


--
-- PostgreSQL database dump complete
--

--
-- PostgreSQL database cluster dump complete

-- Table: public.translation_values_environments

-- DROP TABLE public.translation_values_environments;

CREATE TABLE public.translation_values_environments
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    translation_key_id integer NOT NULL,
    language_id integer NOT NULL,
    value character varying(2000) COLLATE pg_catalog."default" NOT NULL,
    environment character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT translation_values_env_pkey PRIMARY KEY (id),
    CONSTRAINT "FK_translation_key_env_value" FOREIGN KEY (translation_key_id)
        REFERENCES public.translation_keys (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_translation_language" FOREIGN KEY (language_id)
        REFERENCES public.languages (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.translation_values_environments
    OWNER to postgres;
