-- Table: public.translation_values_environments

-- DROP TABLE public.translation_values_environments;

CREATE TABLE public.translation_values_environments
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    translation_key_id integer NOT NULL,
    language_id integer NOT NULL,
    value character varying(2000) COLLATE pg_catalog."default" NOT NULL,
    environment character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT translation_values_env_pkey PRIMARY KEY (id),
    CONSTRAINT "FK_translation_key_env_value" FOREIGN KEY (translation_key_id)
        REFERENCES public.translation_keys (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_translation_language" FOREIGN KEY (language_id)
        REFERENCES public.languages (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.translation_values_environments
    OWNER to postgres;


CREATE TABLE public.translation_values_auto_translate
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    translation_key_id integer NOT NULL,
    language_id integer NOT NULL,
    value character varying(2000) COLLATE pg_catalog."default" NOT NULL,
    reference_value character varying(2000) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT translation_values_auto_t_pkey PRIMARY KEY (id),
    CONSTRAINT "FK_translation_auto_t_value" FOREIGN KEY (translation_key_id)
        REFERENCES public.translation_keys (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_translation_language" FOREIGN KEY (language_id)
        REFERENCES public.languages (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.translation_values_auto_translate
    OWNER to postgres;

ALTER TABLE public.translation_values_auto_translate
    ADD CONSTRAINT un_translation_values_auto_trans UNIQUE (translation_key_id, language_id);
   